### ISSUE TITLE
How to deal with multiple chromosomes?

### ISSUE THREAD

**Issue by SC-Duan** [bloosnail/LAIT#3]
Hi,
Can LAIT deal with multiple chromosomes? I have a ped file including 12 chromosomes. After running lait.pl, I got the message,
Reading SNP positions from chr.pos
Positions in file chr.pos are not legal
9035
I found some positions were not increasing, for examples, the position 9035 follows 44347398.
44344190
44344219
44344627
44344717
44345668
44345773
44345865
44347328
44347337
44347377
44347398
9035
9108
9176
9253
9262
9282
9320
9510
10464
10517
10943
11756
11792
11808
11816
11863
11870
11883
11905
11928
11979
What is the problem？
Thank you!

**Comment by daniel-hui** [comment]
Hello, 

Generally all local ancestry inference software should be run per chromosome. However, the errors you report are not from lait.pl but one of LAI software so you may want to check the corresponding software's documentation. Please let me know if you're still having issues.

Daniel

**Comment by SC-Duan** [comment]
Thank you!
Additionally, can I merge 12 chromosomes to a super chromosome for calculating?
If I run the soft per chromosome, can I calculate the mean value of 12 chromosomes as results?

**Comment by daniel-hui** [comment]
No, don't merge all chromosomes in to one. Yes you can calculate the mean value of all chromosomes, but should scale each chromosome's contribution based on its size relative to the total size of the genome you're working with.

**Comment by SC-Duan** [comment]
Thank you!
